### ISSUE TITLE
add ability to provide username & password configuration

### ISSUE THREAD

**Issue by srinivasupadhya** [ashwanthkumar/gocd-build-github-pull-requests#1]
these will be new fields that you will accept from user on UI as well. I will update the sample git plugin for reference.

**Comment by ashwanthkumar** [comment]
For Github in our case, do you think having the credentials at the environment would be fine? Since generally folks wouldn't have a different credentials for each github repository isn't?

**Comment by srinivasupadhya** [comment]
I think it should be ok for the user to enter username & password for every repo once vs mandating user to use the same credentials across repos?

**Comment by ashwanthkumar** [comment]
:) How about we say users can override credentials for every repo (optionally), if they choose not to, I would fall back the default one?

**Comment by srinivasupadhya** [comment]
Yes. I was going to suggest the same. May be you can take the defaults once Go allows "global/default plugin configuration" on plugins page :+1:

**Comment by srinivasupadhya** [comment]
will do this once https://github.com/ashwanthkumar/gocd-build-github-pull-requests/pull/14 goes in.
