### ISSUE TITLE
Feature request: status badge in a Bitbucket (stash) pull request

### ISSUE THREAD

**Issue by uprial** [ashwanthkumar/gocd-build-github-pull-requests#101]
Hi,

In BitBucket there is a possibility to add a build result to a commit
https://developer.atlassian.com/bitbucket/server/docs/latest/how-tos/updating-build-status-for-commits.html#Updating_build_results

Could you please add such integration to your plugin?

**Comment by ashwanthkumar** [comment]
@uprial We don't know the status of a particular commit in this plugin. You might want to raise this request against the build-notifier plugin (https://github.com/gocd-contrib/gocd-build-status-notifier).
