### ISSUE TITLE
Which environment variables are available?

### ISSUE THREAD

**Issue by grug** [ashwanthkumar/gocd-build-github-pull-requests#102]
In the readme, the following is stated:

> PR details (id, author etc.) will be available as environment variables for tasks to consume.

Which details are available and what are their respective environment variable names?

Thanks,
Dave

**Comment by ashwanthkumar** [comment]
@grug I've updated the [README](https://github.com/ashwanthkumar/gocd-build-github-pull-requests/blob/master/README.md#github) with the list of environment variables available when using Github PR plugin. 

I'm also attaching that table here for your reference.
 
 | Environment Variable | Description |
 | --- | --- |
 | PR_BRANCH | Pull Request was submitted **from** this branch. Eg. `feature-1` |
 | TARGET_BRANCH | Pull Request was submitted **for** this branch. Eg. `master` |
 | PR_URL | Pull Request URL on the Github |
 | PR_AUTHOR | Name of the user who submitted the Pull Request |
 | PR_AUTHOR_EMAIL | Email address of the author who submitted the Pull Request. **Note**: This is subject to availability on their Github profile.|
 | PR_DESCRIPTION | Description of the Pull Request |
 | PR_TITLE | Title of the Pull Request |

**Comment by grug** [comment]
Thank you very much!
