### ISSUE TITLE
Execution dir is different than branch dir

### ISSUE THREAD

**Issue by mynkow** [ashwanthkumar/gocd-build-github-pull-requests#104]
We have a github repository. To version our software we use gitversion => https://github.com/GitTools/GitVersion

So when you invoke gitversion.exe within the repository directory you receive a version relevant to the current branch.

When we use FB plugin the gitversion.exe output is always from a different branch which is strange. It seems like the execution directory is different than the directory where the current branch is checked out. Let me give you an example.

We have two branches:
master - this branch is version 1.0.0 and this is the output from gitversion
release-2.0.0 - when we commit to this branch the FB plugin properly triggers and checks out the correct branch. However executing gitversion returns version `1.0.1` which is relevant for master branch.

Could you please give some more information how this plugin works internally so we can trace and fix it?

10x

https://github.com/ashwanthkumar/gocd-build-github-pull-requests/blob/5724c16d8fa6765b90d6ab3599b3039b1d2793c7/src/main/java/in/ashwanthkumar/gocd/github/GitHubPRBuildPlugin.java#L213

**Comment by ashwanthkumar** [comment]
The first time a repository is configured with this plugin, it builds the master branch. Any consecutive pushes to different branches would build that particular commit. May be that's the behaviour you're seeing?

**Comment by mynkow** [comment]
Yeah, I noticed this. However what I described happens all the time. The only way to fix this is to set the default branch to the branch which I expect the execution to happen and then everything works but this makes the plugin `non sense`

**Comment by mynkow** [comment]
Anyway, I am moving to other CI. This has really bad support.
