### ISSUE TITLE
Support Same Material URL Using Different Base Branch

### ISSUE THREAD

**Issue by StephenMP** [ashwanthkumar/gocd-build-github-pull-requests#106]
# Scenario
I have a git repository with a **master** branch and a **hotfix** branch. I want to have a PR Builder Pipeline for both branches. I want a pull request for the **master** branch to trigger a PR Builder Pipeline for pull requests into **master** branch and the **hotfix** branch to trigger a PR Builder Pipeline for pull requests into **hotfix**.

# Issue
I have successfully created a PR Builder Pipeline for the **master** branch.

When I attempt to create a PR Builder Pipeline for the **hotfix** branch which points to the same material URL, I receive the following error:

![image](https://user-images.githubusercontent.com/1134278/27750868-edfb3838-5d96-11e7-8d71-bd9b7eaa6084.png)

# Request
I should be able to add multiple PR Builder Pipelines pointing to the same repository using a different base branch. Then, based off of the base branch of a pull request, the PR Builder Pipeline with the corresponding base branch is triggered.

**Comment by ashwanthkumar** [comment]
@StephenMP This is a limitation in GoCD's SCM design not to support multiple SCMs with the same name. Having said that the plugin also doesn't have support for building the pipeline for a specific target branch. 

What I mean by that is we use the default branch only to build the first time and a branch we know we can always checkout to during cleanup process. PR plugin always checks out the particular version (latest SHA in a PR) and builds that. We don't support building merging of PR branch and the target branch to check compatibility.

HTH
