### ISSUE TITLE
Unable to add "Github" type material via Go API

### ISSUE THREAD

**Issue by williamsbdev** [ashwanthkumar/gocd-build-github-pull-requests#110]
We tried to create a new pipeline with the "Github" type material via the Go API. We were unable to do so. We would love to use this plugin but we cannot manage all the PR pipelines manually. Is there a known way to handle these new PR pipelines programmatically?

**Comment by ashwanthkumar** [comment]
I have personally not used custom SCMs with API on GoCD. But I guess it should be something like

1. Create a global SCM Material using [SCMs#CreateSCMObject](https://api.gocd.org/current/#create-a-scm-object)
2. [Create a new pipeline](https://api.gocd.org/current/#create-a-pipeline) with the above custom SCM as one of the materials

**Comment by williamsbdev** [comment]
@ashwanthkumar - Thank you! I'll have to check out the plugin SCM type.

**Comment by williamsbdev** [comment]
@ashwanthkumar -
