### ISSUE TITLE
PR does not trigger pipeline to start

### ISSUE THREAD

**Issue by santanp** [ashwanthkumar/gocd-build-github-pull-requests#114]
I have configured 2 pipelines in same group against two different github repos.
pipeline 1 -> gets trigged on new PR and update commit on PR. Works perfect.
pipeline 2 -> Similarly configured againt another repo but this does not trigger pipeline 2 to start. I don't even get any errors.

Can someone please help me understand what might be the issue.

**Comment by ashwanthkumar** [comment]
@santanp Can we close this issue?

**Comment by santanp** [comment]
@ashwanthkumar : Ya, Deleting the flyweight folder associated with the material solved of the issues for me. Thanks
