### ISSUE TITLE
Shallow Clone Branch

### ISSUE THREAD

**Issue by thomaslloyd** [ashwanthkumar/gocd-build-github-pull-requests#116]
Is it possible to set this plugin to shallow clone the pull request branch? We are noticing large durations for fetching materials, and this is because we have a big repo with a long history. It would really help if we only shallow cloned the branch.

**Comment by ashwanthkumar** [comment]
@thomaslloyd We now have a https://github.com/ashwanthkumar/gocd-build-github-pull-requests/releases/tag/1.4.0-RC available which has fixes for this. Thanks to @gnandiga. It would be great if you can give it a try and let us know your feedback.

**Comment by ashwanthkumar** [comment]
I'm closing this for now, please feel free to re-open it if needed.
