### ISSUE TITLE
Build only Open PRs

### ISSUE THREAD

**Issue by ashwanthkumar** [ashwanthkumar/gocd-build-github-pull-requests#13]
Today we're not checking for a PR being open / closed while scheduling a build for them. We should schedule a build only if the PR is still Open.

**Comment by srinivasupadhya** [comment]
This is party taken care off by https://github.com/ashwanthkumar/gocd-build-github-pull-requests/pull/14. Since the plugin will now send changes to PRs (add of new PR/update to existing PR) it could be assumed that the PR is open?

**Comment by srinivasupadhya** [comment]
closing this for now. will reopen if someone complains.
