### ISSUE TITLE
Run multiple instances of the job

### ISSUE THREAD

**Issue by SahilLone** [ashwanthkumar/gocd-build-github-pull-requests#140]
I am using gocd with elastic agents on Kubernetes.
As of now only one job runs even when multiple PR's are submitted and multiple commits. 
Is it possible to make it happen to build all of the commits at once ,since the agents are available.

**Comment by ashwanthkumar** [comment]
If your PR build pipeline  have only one stage, GoCD by design can't run multiple instances. 

While I've not tried personally,if your pipeline has multiple stages try disabling pipeline locking and if that helps.
