### ISSUE TITLE
Cannot see github option in material section for GoCD v20.1.0

### ISSUE THREAD

**Issue by monikakatiyar16** [ashwanthkumar/gocd-build-github-pull-requests#141]
**Issue:**
- Not able to see github option in Materials section on UI. Also unable to see any logs for the plugin in /var/log/go-server folder

**Steps to reproduce:**
- Downloaded and installed "github-pr-poller-1.4.0-RC2.jar" in goserver/plugin/external folder (in my case, /var/lib/go-server/plugins/external).
- Added .github file in folder /var/go with file ownership of go user.
- Restarted the go-server using systemctl restart go-server.
-  Able to see the plugin in the UI
![image](https://user-images.githubusercontent.com/20658430/74092417-60cb6800-4ae9-11ea-8d60-227b820a80c6.png)

I cannot see any logs in /var/log/go-server for github pr poller. I can see logs for github status notifier. With older 18.5 version of GoCD, it was working and I could also see the logs for the plugin at this location.

From UI, I cannot see the option Github in Materials section. 
![Github](https://user-images.githubusercontent.com/20658430/74092435-ca4b7680-4ae9-11ea-8ade-e876683bf9ac.png)

Is there something wrong that I am doing there?

**Comment by monikakatiyar16** [comment]
Sorry. There's no issue with the plugin. It's just the new look that got me confused. I am not able to see the github option here. But once after creating the pipeline with git creds here, on editing the pipeline, I am able to see the github option!

**Comment by mrmanc** [comment]
Can this be reopened as I feel it is an issue. It would be good to create a pipeline with a `Github` material type from the start. Is there a reason why this plugin’s material type can’t appear in this list?

As it is, to create a pull request pipeline I have to give it a dummy material that I later remove after the pipeline is created when I have been able to add the new `Github` material.

**Comment by ashwanthkumar** [comment]
@mrmanc This is not an issue with the plugin, it's an issue with GoCD itself. Please consider opening this issue at GoCD repo directly.

**Comment by mrmanc** [comment]
Will do… thanks 👍
