### ISSUE TITLE
Environment variables are not present as defined in documentation

### ISSUE THREAD

**Issue by austinorth** [ashwanthkumar/gocd-build-github-pull-requests#142]
I tried to set up a pipeline for building PRs using this documentation, and found it very frustrating, as all of the screenshots are out of date the the environment variables do not appear as defined in the documentation. For example, I tried to tag a Docker image called `fact` using the `PR_BRANCH` variable and ended up with the following:
![job_fail](https://user-images.githubusercontent.com/31007285/77768095-612bae00-7018-11ea-9704-d19b0ceb72d8.png)
I did a `printenv` as a task in the pipeline just to see what variables were available, and after digging through the list, found the variable, but it has a _prefix_ generated from the name of the _source material_:
![environment](https://user-images.githubusercontent.com/31007285/77768213-87514e00-7018-11ea-8f70-5ed6dda181c3.png)
This is mentioned nowhere in the documentation, and is critical to being able to use the plugin correctly. I notice people have had similar frustrations in #105, and it would make a lot of sense to update the readme to clarify this and to update the screenshots as well.

**Comment by ashwanthkumar** [comment]
Thanks for the feedback @austinorth -- I accept Pull Requests for the documentation changes.

**Comment by ashwanthkumar** [comment]
Closed by #147
