### ISSUE TITLE
Support for BitBucket Server 7

### ISSUE THREAD

**Issue by Gasparfx** [ashwanthkumar/gocd-build-github-pull-requests#157]
Hello!

"BitBucket Server 7.x no longer automatically creates the required refs for pull requests"

So for refs to update we need to call changes api.

How they do it in jenkins:
https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/294/files

Without it we have to manually click Diffs tab for build to trigger.

More info:
https://jira.atlassian.com/browse/BSERV-12284?focusedCommentId=2389584&%5Bimprove+performance

May be connected:
https://github.com/ashwanthkumar/gocd-build-github-pull-requests/issues/139

**Comment by ashwanthkumar** [comment]
Please check https://github.com/ashwanthkumar/gocd-build-github-pull-requests/issues/46. We've decided long back we'll not support API based integration in this plugin.
