### ISSUE TITLE
Any plans to support gitlab? 

### ISSUE THREAD

**Issue by jefftrimm** [ashwanthkumar/gocd-build-github-pull-requests#22]
Any plans to support gitlab?

**Comment by srinivasupadhya** [comment]
we added support for ref-spec based branch builds ([reference](https://groups.google.com/d/msg/go-cd-dev/Rt_Y5G2VkOc/vQvK8vqCVoYJ)). could not find ref-spec for bitbucket & gitlab. i installed gitlab locally and tried what i could find on the internet. nothing seems to work. i couldn't find anything that says they dont support though. there is this [issue](https://bitbucket.org/site/master/issue/5814/reify-pull-requests-by-making-them-a-ref) filed with bitbucket.

**Comment by paulclarkin** [comment]
This issue is on [Gitlab Feature Requests](http://feedback.gitlab.com/forums/176466-general/suggestions/7126843-expose-merge-requests-as-refspecs) too.

**Comment by paulclarkin** [comment]
Is there any information that can be gained from studying what [this Jenkins plugin](https://github.com/timols/jenkins-gitlab-merge-request-builder-plugin) does?

**Comment by srinivasupadhya** [comment]
IMHO, this plugin is for ref-spec based branch builds. if we plan to use APIs to do the same i would strongly suggest having a seperate codebase to keep this from getting compilcated. will leave the final call for @ashwanthkumar

**Comment by ashwanthkumar** [comment]
I agree with @srinivasupadhya if we're going to use APIs then we need to build it as a separate plugin. Closing the ticket.

**Comment by ashwanthkumar** [comment]
For archival purpose -- we now have support for building Merge Requests from Gitlab as part of https://github.com/ashwanthkumar/gocd-build-github-pull-requests/releases/tag/v1.4.0-RC4.
