### ISSUE TITLE
Does not seem to read oath value from .github

### ISSUE THREAD

**Issue by stevendgonzales** [ashwanthkumar/gocd-build-github-pull-requests#23]
I can only get the plugin to work when suppllying login and password.  The GitHub provider.addConfig doe s not seem to load the oauth setting https://github.com/ashwanthkumar/gocd-build-github-pull-requests/blob/master/src/main/java/in/ashwanthkumar/gocd/github/provider/github/GitHubProvider.java#l30

I am running go-server version 15.1.0-1845

**Comment by srinivasupadhya** [comment]
@ashwanthkumar - Is this fixed as part of #17? If so can you please close this?

**Comment by ashwanthkumar** [comment]
@srinivasupadhya Yes this should be handled now.
