### ISSUE TITLE
Pre-release?

### ISSUE THREAD

**Issue by cnorthwood** [ashwanthkumar/gocd-build-github-pull-requests#24]
Hi,

I was wondering what the state of this plugin was? It's linked to from go.cd, but the releases are all marked as pre-release. I've tried deploying it on my Go instance but I'm getting odd behaviour - it tries to build a single pull request (normally a really old one that was merged ages ago) after the master starts, then the build fails, and then never tries to build any more.

**Comment by srinivasupadhya** [comment]
assuming you are trying gihub - can you post `plugin-github.pr.log` here so we can see what's happening. 

for pre-release - @ashwanthkumar do you think we can make a stable release?

**Comment by ashwanthkumar** [comment]
@srinivasupadhya Yup we can.

**Comment by srinivasupadhya** [comment]
@ashwanthkumar - would be great if we could fix #17 before the stable release.

**Comment by ashwanthkumar** [comment]
@srinivasupadhya I'll complete it sometime today / tomorrow and push it. We should be able to do a stable release by EOW then.

**Comment by cnorthwood** [comment]
This is what it contains:

    2015-05-11 14:01:16,328  INFO [89@MessageListener for MaterialUpdateListener] GitHubPRBuildPlugin:52 - new commits: 26
    2015-05-11 14:01:17,118  INFO [90@MessageListener for MaterialUpdateListener] GitHubPRBuildPlugin:52 - new commits: 15
    2015-05-11 14:01:21,234  INFO [91@MessageListener for MaterialUpdateListener] GitHubPRBuildPlugin:52 - new commits: 103
    2015-05-11 14:01:35,392  INFO [88@MessageListener for MaterialUpdateListener] GitHubPRBuildPlugin:52 - new commits: 290

and then nothing since (even though I have raised PRs)

**Comment by srinivasupadhya** [comment]
@ashwanthkumar - EOW is good with me. When you are fixing #17 may be you can fix [this](https://github.com/ashwanthkumar/gocd-build-github-pull-requests/blob/master/src/main/java/in/ashwanthkumar/gocd/github/provider/github/GHUtils.java#L65) as well. (you will need to read from `~/.github` as well i suppose, since we claim support)

**Comment by srinivasupadhya** [comment]
@cnorthwood - we are working on GA release. Once thats out with the https://github.com/ashwanthkumar/gocd-build-github-pull-requests/pull/25 we should be able to turn on debug logs & see whats happening. Till then you can may be check if there are any hung process (git) & let us know what version of git is installed on your server box?

**Comment by stevendgonzales** [comment]
It would be nice to fix #31 before stable release as the plugin is broken on repos that have git submodules.  I'm happy to submit a PR to fix if needed.

**Comment by srinivasupadhya** [comment]
we have a GA now. closing this.
