### ISSUE TITLE
UrlValidator does not correctly validate custom domains

### ISSUE THREAD

**Issue by kerrmarin** [ashwanthkumar/gocd-build-github-pull-requests#26]
Hi,

Imagine I have an instance of Stash running behind my firewall using a custom URL scheme:

http://stash.vm.hello.world

A valid URL for a material will be:

http://stash.vm.hello.world/scm/project/my_repo.git

When using the default, built-in GO Git material, this URL is valid. When using Stash material type, it reports the URL as invalid.

However, this fails validation when adding the material for "Stash" (it may fail for other ones too)

**Workaround**: A current workaround for this is to use the IP address of the machine you are wanting to talk to instead of its hostname.

**Comment by srinivasupadhya** [comment]
this should be simple enough to fix. will do when i find time. thanks for reporting.

**Comment by srinivasupadhya** [comment]
fixed with https://github.com/ashwanthkumar/gocd-build-github-pull-requests/commit/9344e0a4e07fe47061cf870efed648c71d4f964d
