### ISSUE TITLE
Unable to configure plugin

### ISSUE THREAD

**Issue by superbeeny** [ashwanthkumar/gocd-build-github-pull-requests#30]
After following the instructions the option,

```
CHECK CONNECTION
check connection failed. {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
```
I'm using github enterprise in the url field.

Nick

**Comment by superbeeny** [comment]
this is the github enterprise poller

**Comment by srinivasupadhya** [comment]
how are you configuring endpoint url? if you are doing through system property, it doesn't work yet because of #17 i think. @ashwanthkumar will be fixing it by EOW is what he said.

**Comment by superbeeny** [comment]
ok I'll wait for the next release to check. Thanks for the update

**Comment by superbeeny** [comment]
one question...do you delete the existing material when you update with the 'github' pr material?

**Comment by srinivasupadhya** [comment]
yes, you can delete the original material, this is a replacement to that!

**Comment by ashwanthkumar** [comment]
@superbeeny Are you using the oauth or username / password based authentication?

**Comment by superbeeny** [comment]
oauth in a .github file in the go user's home directory

**Comment by superbeeny** [comment]
Found the first issue, when you hit copy for the clone url in GHE it has the suffix .git and it appears the code in GHUtils does not expect this for enterprise github. As soon as I removed the .git suffix from the url it started working.

**Comment by ashwanthkumar** [comment]
Thanks for pointing it out. It looks like the clone is failing, we don't seem to be passing the auth from ~/.github while doing cloning. I've created an issue to track it #37.

**Comment by ashwanthkumar** [comment]
@superbeeny The thing is, we use the file at `~/.github` only for PR access. There's an implicit assumption that SSH keys are configured on the agents to connect to Github for cloning the repos. 

@srinivasupadhya What are your thoughts on this?

**Comment by srinivasupadhya** [comment]
We could add support for `~/.github` file access as well. The code [here](https://github.com/ashwanthkumar/gocd-build-github-pull-requests/blob/master/src/main/java/in/ashwanthkumar/gocd/github/GitHubPRBuildPlugin.java#L265) needs to handle that bit. It could delegate it to provider if `username` & `password` is not available & `GithubProvider` could add them if available in `~/github`.

**Comment by srinivasupadhya** [comment]
@ashwanthkumar - if #37 is the only issue, can we close this?
