### ISSUE TITLE
Gerrit FastForwardOnly - code not refresh after second commit

### ISSUE THREAD

**Issue by aksk08** [ashwanthkumar/gocd-build-github-pull-requests#33]
Build is not run when change is updated (not created). Case:
I have private git and gerrit. Projects in gerrit are defined with Submit Type = FastForwardOnly.

In model pipeline materials is pointed to my gerrit. Pipeline is simple: when some changes are noticed  some maven task should be run and the result send to gerrit as verification status.

When I push the first commit it starts a new build - everything is OK.
But when the code is broken and then repaired, new code is not noticed. First commit - build is ended with error, verification is set to -1 (OK). Some correctness to code is done and it is sent to gerrit, with the same ChangeID (because of the Submit Type). In gerrit new patch is displayed but no reaction in pipeline. Even after manual trigger code is not updated.

**Comment by srinivasupadhya** [comment]
Thanks for reporting.

Do you think https://github.com/ashwanthkumar/gocd-build-github-pull-requests/pull/34 fixes it? or do you think there is something more to be done?

**Comment by srinivasupadhya** [comment]
Also, I have written a [build status notifier](https://github.com/srinivasupadhya/gocd-build-status-notifier) with the intention to update changeset with build status. It currently supports Github PR & Stash PR updates. Im trying to figure out how to update changeset with status. It would be great if you could help me out with anything!

**Comment by aksk08** [comment]
Hi,
I think that the change should solve the problem.

I am using <a href="https://gerrit-documentation.storage.googleapis.com/Documentation/2.11/cmd-review.html"> gerrit review</a> command to add comments and review to a patch. In pipeline there is a task which sends verification status via custom command, where gerrit review looks like following:

ssh myGerrit gerrit review --label Verified=$1 $2. 

Parameters are set in custom command as attributes. As you can see it runs as ssh, not http.

**Comment by srinivasupadhya** [comment]
> ssh myGerrit gerrit review --label Verified=$1 $2.

great. i will give that a try & let you know if i face more issues.

**Comment by srinivasupadhya** [comment]
i have added support for [gerrit status notifier](https://github.com/srinivasupadhya/gocd-build-status-notifier/releases).

**Comment by aksk08** [comment]
thanks.
I have installed it, added system properties
(go.plugin.build.status.go-server, go.plugin.build.status.gerrit.username,
go.plugin.build.status.gerrit.password) and no changes in the gerrit. Maybe
properties are not correct?


2015-06-26 18:54 GMT+02:00 srinivas upadhya <notifications@github.com>:

**Comment by srinivasupadhya** [comment]
Thanks for giving it a shot & reporting the bug! I had forgotten to add support for system property with gerrit. I have updated the gerrit plugin with the required changes & docs for the same. Can you reinstall plugin & give it a try? thanks.

**Comment by aksk08** [comment]
Right now I have got 401 error. I have used the same URL which is set in
the Gerrit Change Set plugin but this time it has not worked. The gerrit
normally  is run via https (only connection from the same machine can be
via http). When URL is changed to https, certificate problem occurs:
sun.security.provider.certpath.SunCertPathBuilderException: unable to find
valid certification path to requested target. So, to solve it I need more
time.

2015-06-29 9:59 GMT+02:00 srinivas upadhya <notifications@github.com>:

**Comment by aksk08** [comment]
Something odd is logged. I have set *https://gerrit.development-ci
<https://gerrit.development-ci>* (this is the intranet server so hostname
is custom) as endpoint and in the log file is:

[65@MessageListener for PluginNotificationListener
] BuildStatusNotifierPlugin:77 - Error occurred. Could not update build
status -
 *URL: http://127.0.0.1:8080/simple-test
<http://127.0.0.1:8080/simple-test>* Revision:
1b60d80a08e4407030aadd3be33839
852fe51212 Build: simple-test-gerrit/14/more-quality-check/4 Result: Passed

It looks like URL is gotten from Gerrit Change Set. Am I right?

I am not able to change url in Gerrit Change Set to https url - validation
error is displayed. This is another case connected with this issue:
https://github.com/ashwanthkumar/gocd-build-github-pull-requests/issues/26.

2015-06-29 13:02 GMT+02:00 Anna Książek <aksk08@gmail.com>:

**Comment by srinivasupadhya** [comment]
> It looks like URL is gotten from Gerrit Change Set. Am I right?

no, if you see [here](https://github.com/srinivasupadhya/gocd-build-status-notifier/blob/master/src/main/java/com/tw/go/plugin/provider/gerrit/GerritProvider.java#L40) im using `go.plugin.build.status.gerrit.endpoint`.

and https://github.com/ashwanthkumar/gocd-build-github-pull-requests/issues/26 is fixed & is available in v1.2

**Comment by aksk08** [comment]
I am not able to set recognized certificate. I have added self-sign
certificate to the /etc/go/truststore file and Gerrit Change Set plugin
works correctly with https. But Gerrit Change Set status notifier still
logs "unable to find valid certification path to requested target". Even
when it is runs with system property
-Djavax.net.ssl.trustStore=/etc/go/truststore. When ssl debug is activated
only certifacate from keystore is logged.


2015-06-30 15:05 GMT+02:00 srinivas upadhya <notifications@github.com>:
