### ISSUE TITLE
Not using ~/.github while doing cloning

### ISSUE THREAD

**Issue by ashwanthkumar** [ashwanthkumar/gocd-build-github-pull-requests#37]
We're not using the credentials from ~/.github while cloning, we only use the username and password from the material configuration.

**Comment by srinivasupadhya** [comment]
just saw - should [this](https://github.com/ashwanthkumar/gocd-build-github-pull-requests/blob/master/src/main/java/in/ashwanthkumar/gocd/github/GitHubPRBuildPlugin.java#L267) & [this](https://github.com/ashwanthkumar/gocd-build-github-pull-requests/blob/master/src/main/java/in/ashwanthkumar/gocd/github/provider/github/GitHubProvider.java#L31) take care of it?

**Comment by ashwanthkumar** [comment]
Oh yes, you're right. We can close this then.

**Comment by srinivasupadhya** [comment]
we closed both #37 & #30. I hope the original issue is fixed!
