### ISSUE TITLE
Plugin still reports version 0.1

### ISSUE THREAD

**Issue by kerrmarin** [ashwanthkumar/gocd-build-github-pull-requests#38]
Hey,

Not a big problem in any way but I updated the plugin this morning, restarted the server, and I noticed that under the plugins page, the version is still 0.1 (in grey just after the plugin name).

![screen shot 2015-05-22 at 09 29 41](https://cloud.githubusercontent.com/assets/2995710/7766857/716d4c56-0065-11e5-9f40-fc55a3253af4.png)

**Comment by ashwanthkumar** [comment]
My bad. Will fix it.

**Comment by ashwanthkumar** [comment]
@kerrmarin Please switch to v1.1 it should be right now.
