### ISSUE TITLE
Username and password is auto-populated during setup

### ISSUE THREAD

**Issue by pastafari** [ashwanthkumar/gocd-build-github-pull-requests#39]
Hi,

I'm trying to setup a Github Pull Request polling branch using the steps in the README. Everything works great when there is no authentication mechanism enabled in Go. However, if I am logged in as a certain user, then the Username and password fields in the material setup get auto-populated as my Go username and password :confused:  Even when I delete those values and save the material, when I re-open the material to edit, they are pre-populated. 

Now, the Check Connection to Github fails (it works when user and password are blank), as my Go credentials are being used instead of my Github credentials stored in `~/.github` 

Why is this happening and how do we get around it? 

See screenshots below:
![check-connection-failed](https://cloud.githubusercontent.com/assets/193407/8053697/b8780b8c-0eb0-11e5-8caf-1b310dbb9369.png)
![check-connection-works](https://cloud.githubusercontent.com/assets/193407/8053698/b8b96d3e-0eb0-11e5-9bc3-8ada7f02c98e.png)

**Comment by ashwanthkumar** [comment]
Do you have your username and password saved on the browser? - I suspect it is that. Can you try and see if you can re-produce the same issue on a different browser which doesn't a password saved for you go-server domain. 

/cc: @srinivasupadhya

**Comment by pastafari** [comment]
@ashwanthkumar I was just doing that when I saw your reply. I think you are right, its my browser thats populating those fields. Very confusing! 

Thanks for the quick reply, I'll close this.
