### ISSUE TITLE
Expose PR Attributes as ENV variables

### ISSUE THREAD

**Issue by ashwanthkumar** [ashwanthkumar/gocd-build-github-pull-requests#4]
Attached is a screenshot for reference properties in github pr plugin in jenkins

![screen shot 2015-02-20 at 3 47 33 pm](https://cloud.githubusercontent.com/assets/600279/6312973/fe8a3386-b9b8-11e4-821f-93c1f278b7ac.png)

**Comment by ashwanthkumar** [comment]
We emit the following environment variables. 

![github_scm_env_props](https://cloud.githubusercontent.com/assets/600279/6313031/852201be-b9bc-11e4-9bc0-13c9088c2aed.png)

PS - `SCM_TEST` is the name of the material.

**Comment by cw-deenbandhu** [comment]
Hi Ashwanth,
I am not able to see all those variables in the console can you please help me out
