### ISSUE TITLE
Git Feature Branch plugin does not respect credentials in ~/.github

### ISSUE THREAD

**Issue by pastafari** [ashwanthkumar/gocd-build-github-pull-requests#40]
I am trying to setup the feature branch plugin to work with a Github repo. There's a few problems:

1. It does not allow me to use a SSH clone URL of the form `git@github.com:...` by saying Invalid URL.
![screen shot 2015-06-09 at 3 01 35 pm](https://cloud.githubusercontent.com/assets/193407/8054737/76b121c2-0eb8-11e5-978b-8f449e786b0c.png)

2. If I use an https URL, then it does not respect my github credentials from ~/.github like the PR plugin does. I understand this might be intentional because Git feature branches need not depend on Github. But it is not clear from the README whether my credentials will be picked from ~/.github or not.

3. It is clear that if I need to use https on Github, then I must use username/password based auth. 

Open questions:
1. Why is the SSH clone URL not supported? That would let me use key based auth on agents.
2. As it stands, I need to use https on Github, but username and password is not mandatory. This makes for a confusing experience.
3. Once we decide on what is the right thing to do, can we please add a section in the README.

Once again, thanks a lot @ashwanthkumar and @srinivasupadhya  for working on this :heart: :heart:

**Comment by srinivasupadhya** [comment]
> Why is the SSH clone URL not supported? That would let me use key based auth on agents.

i think `URLUtils.isValidURL(url)` is not validating correctly. please log a bug & i will fix it when i can. for now you can bypass the Go Server validation by directly editing the config xml & using ssh based url.

> I need to use https on Github, but username and password is not mandatory

thats because github allows cloning of public repositories without requiring any credentials.

> Once we decide on what is the right thing to do, can we please add a section in the README.

you are right. 'git feature branch' plugin is a independent plugin & does not support `~/.github` for authentication.

> Once again, thanks a lot @ashwanthkumar and @srinivasupadhya for working on this :heart: :heart:

welcome :)

**Comment by srinivasupadhya** [comment]
closing this for now. feel free to raise separate issues for specific problems.
