### ISSUE TITLE
Deleting a pipeline does not delete the corresponding SCM (material) entry in config file

### ISSUE THREAD

**Issue by aps-sids** [ashwanthkumar/gocd-build-github-pull-requests#41]
If we delete a pipeline using a Github material, the SVN entry is not removed from config file. Hence, while adding material for "Git feature branch", we can't use the previous material name since a duplicate entry exists in the config file. Refer following screenshot.

![screen shot 2015-06-11 at 7 27 38 pm](https://cloud.githubusercontent.com/assets/2363074/8108794/495cada4-1070-11e5-90c8-394ef14a255e.png)

**Comment by srinivasupadhya** [comment]
yes. that is by design of Go. SCMs (pluggable) are treated as global entities & they will need to be removed separately. refer to do section of https://github.com/gocd/gocd/issues/818.

**Comment by aps-sids** [comment]
I think there should be an option to use existing SCM in that case. Is there something planned?

**Comment by srinivasupadhya** [comment]
that is also something that Go needs to provide ability for. there is an issue logged for it - https://github.com/gocd/gocd/issues/1078
