### ISSUE TITLE
Support for build status context

### ISSUE THREAD

**Issue by arthurk** [ashwanthkumar/gocd-build-github-pull-requests#44]
Hi,

in github it is possible to report the status with a specific context: https://developer.github.com/v3/repos/statuses/

You can check the Docker repo to see how it looks: https://github.com/docker/docker/pull/13959

It would be nice if this plugin could support this feature.

**Comment by srinivasupadhya** [comment]
build status is supported via a separate [plugin](https://github.com/srinivasupadhya/gocd-build-status-notifier) & it already supports context in build status - sample: https://github.com/srinivasupadhya/sample-repo/pull/7

**Comment by arthurk** [comment]
perfect, thanks! i'm closing this ticket then
