### ISSUE TITLE
ssh url not supported for git-fb

### ISSUE THREAD

**Issue by palinf** [ashwanthkumar/gocd-build-github-pull-requests#45]
When creating a new material of type **Git Feature Branch**
The material plugin does not accept ssh git urls (as the classical git material accept) 

Url like ```ssh://myServer/myPath/myProject.git```
The following error is displayed: Invalid Url

**Comment by waynedovey** [comment]
It would be good to also allow user@myserver:mypath/myproject.git. Please let me know if that's possible?

**Comment by srinivasupadhya** [comment]
@ashwanthkumar - i have turned off url validation for now ([commit](https://github.com/ashwanthkumar/gocd-build-github-pull-requests/commit/e4cad16afc0db90e7b264048e01ddbbcea1e5ff3)). Will fix it once i figure out a regex for http/https/ssh/file etc.

**Comment by ashwanthkumar** [comment]
I'm closing this.
