### ISSUE TITLE
Make pull request creator's email available as an environment variable for Stash provider

### ISSUE THREAD

**Issue by kerrmarin** [ashwanthkumar/gocd-build-github-pull-requests#48]
Hey,

It would be great to have available the email of the user that created the pull request for notifications etc.

Thanks!

**Comment by ashwanthkumar** [comment]
@kerrmarin It is already available as `GO_SCM_<SCM_NAME>_AUTHOR_EMAIL`.

**Comment by ashwanthkumar** [comment]
I'm closing this issue.

**Comment by kerrmarin** [comment]
Hi there @ashwanthkumar, thanks for replying to this. I don't think it's available, these are the variables that are available (from the Go console):

GO_SERVER_URL
GO_TRIGGER_USER' to value 'changes'
GO_PIPELINE_NAME' to value 'app-pr-test'
GO_PIPELINE_COUNTER' to value '1075'
GO_PIPELINE_LABEL' to value '1075'
GO_STAGE_NAME' to value 'Test'
GO_STAGE_COUNTER' to value '1'
GO_JOB_NAME' to value 'Test-All'
GO_REVISION_SCRIPTS
GO_TO_REVISION_SCRIPTS
GO_FROM_REVISION_SCRIPTS
GO_SCM_APP_LABEL
GO_SCM_APP_URL
GO_SCM_APP_PR_ID' to value '1071

**Comment by ashwanthkumar** [comment]
@kerrmarin Do you by chance have `go.plugin.github.pr.populate-details` properties set to "N"? 

Ref - https://github.com/ashwanthkumar/gocd-build-github-pull-requests/blob/master/src/main/java/in/ashwanthkumar/gocd/github/provider/github/GitHubProvider.java#L77

**Comment by kerrmarin** [comment]
Ah, apologies. My provider is actually Stash, not Github :). Do you know if this is available for Stash as well as Github?

**Comment by ashwanthkumar** [comment]
Unfortunately we don't have that support for Stash. Would you be willing to submit a PR with that change? We would be glad to merge that in.
