### ISSUE TITLE
Remove jGit dependency in favour git command line

### ISSUE THREAD

**Issue by ashwanthkumar** [ashwanthkumar/gocd-build-github-pull-requests#52]
Issues like #49, #51 and #29 all revolve around jGit. 
@srinivasupadhya I'm thinking of moving away from jGit completely in favour git command line. Thoughts?

**Comment by srinivasupadhya** [comment]
yes we could, in which case not finding git in path will fail & say the same?

**Comment by ashwanthkumar** [comment]
Yes.
