### ISSUE TITLE
Use OAuth Token while using HTTPs urls for cloning

### ISSUE THREAD

**Issue by ashwanthkumar** [ashwanthkumar/gocd-build-github-pull-requests#54]
Ref - https://github.com/blog/1270-easier-builds-and-deployments-using-git-over-https-and-oauth

**Comment by linxcat** [comment]
I'm just going to leave a +1 here because this is a feature is extremely important for github enterprise environments especially, where tokens are a common way of authenticating through LDAP.

**Comment by ashwanthkumar** [comment]
I'm marking this as closed since we've moved to use only `git` command line client (unlike jGit as default in older releases) and these work out of the box for them. 

@linxcat Let me know if that's not the case.
