### ISSUE TITLE
Clone fails on mac as of release 1.2.1

### ISSUE THREAD

**Issue by jx1471** [ashwanthkumar/gocd-build-github-pull-requests#55]
Default macosx agent path has spaces that 'git-cmd' does not handle properly in release 1.2.1. This prevents proper cloning of repos. Pull request 7 for 'git-cmd' resolves this issue, suggest another minor release since this issue greatly affects compatibility with macosx. 

See pull request for details: 
https://github.com/srinivasupadhya/git-cmd/pull/7

**Comment by ashwanthkumar** [comment]
@jx1471 Please checkout the v1.2.2 on https://github.com/ashwanthkumar/gocd-build-github-pull-requests/releases/tag/v1.2.2

Thanks :+1:
