### ISSUE TITLE
Dependency com.thoughtworks.go:git-cmd not in Maven Central

### ISSUE THREAD

**Issue by tanob** [ashwanthkumar/gocd-build-github-pull-requests#62]
I'm trying to get this plugin building in my machine but looks like `git-cmd` is not in Maven Central.

Can you please put some building instructions in README or put the dependency in Maven?

**Comment by tanob** [comment]
I had to manually do this to get the plugin building:

```
git clone https://github.com/srinivasupadhya/git-cmd.git
cd git-cmd
mvn install -Dversion=1.0
```

**Comment by ashwanthkumar** [comment]
@tanob I'm sorry for the trouble. Yeah we don't have `git-cmd` published on Maven Central. Will get that done soon. Thanks.

**Comment by lenucksi** [comment]
:+1:
