### ISSUE TITLE
Run multiple PRs in parallel

### ISSUE THREAD

**Issue by virtuald** [ashwanthkumar/gocd-build-github-pull-requests#63]

**Comment by ashwanthkumar** [comment]
This is currently not possible by GoCD's design unless your build pipeline has multiple stages.

**Comment by mlennon-lumere** [comment]
I don't see this documented in any gocd issue or on the website, although I've certainly always seen GoCD operate how you say.  Do you know if there is any discussion on a feature to allow parallel stage execution across different pipeline build instances?

**Comment by ashwanthkumar** [comment]
@mlennon-lumere Related issue - https://github.com/gocd/gocd/issues/2329

**Comment by ashwanthkumar** [comment]
Closing as it's currently not possible in GoCD. Once https://github.com/gocd/gocd/issues/2329 lands we can re-open this issue.
