### ISSUE TITLE
FeatureBranch - merge to master does not trigger pipeline execution

### ISSUE THREAD

**Issue by akurkin** [ashwanthkumar/gocd-build-github-pull-requests#65]
hey guys,
in the following scenario:

1. cut new `feature/XXX` from `master`
2. push `feature/XXX` to remote
3. pipeline executed for `feature/XXX`
4. PR gets reviewed and somebody decides to merge it to master
5. `feature/XXX` gets merged into `master`
6. go.cd notices the changes, but *doesn't start the pipeline*

Is this expected? is there a way to resolve this?

Thanks,
Alex

**Comment by ashwanthkumar** [comment]
Our usual approach is to use one for building master and one for all PRs. If you merged the changes to master, it would only trigger the master branch building pipeline and not the pipeline that's building the PR. 

Are you seeing any issues in this behaviour?

**Comment by akurkin** [comment]
Can you please clarify:
so for each application, you have 2 pipelines: one pipeline builds a pull request, the other pipeline builds master branch?

If so, how does the plugin know to skip master branch?

**Comment by ashwanthkumar** [comment]
The plugin doesn't know :) The plugin is meant to be used only on the PR build pipeline. For the other, you should be using Git material directly.

**Comment by akurkin** [comment]
ok, got it. thanks for clarification :+1: :bow:

**Comment by ashwanthkumar** [comment]
@akurkin Let me know if the README instructions aren't clear. If you would like to change the documentation for the better, please send in a PR.

**Comment by akurkin** [comment]
@ashwanthkumar sure, I will read it thoroughly again and see if there's a way to improve to clear out confusion for future users :)

**Comment by ashwanthkumar** [comment]
:+1:
