### ISSUE TITLE
Add an option to specify default branch for the repo

### ISSUE THREAD

**Issue by ashwanthkumar** [ashwanthkumar/gocd-build-github-pull-requests#66]
Not always the default branch in a git repository is `master`. There're instances where there's a new master in the making and we want to test the changes against that. Adding an option to provide a default branch in the configuration like the `Git` plugin would be really useful.

**Comment by rizotas** [comment]
+1

**Comment by hfortegcmlp** [comment]
+1

**Comment by manifest** [comment]
+1

**Comment by ashwanthkumar** [comment]
Someone wants to send a PR for this? I would be happy to review and merge it in.

**Comment by gunnarx** [comment]
+1 :+1:

**Comment by arvindsv** [comment]
@ashwanthkumar: I am thinking about making this change. I haven't spent too much time on this codebase, though. From a quick glance, I found that it should be possible to get the branch from the user and pass it along to the git-cmd component. The git-cmd component [seems ready to](https://github.com/ashwanthkumar/git-cmd/blob/4e00e086e6a92ac4706470039ea93393beb26794/src/com/tw/go/plugin/model/GitConfig.java#L18) accept the branch, but it is not a part of the user-defined config and it is not passed in to GitConfig [here](https://github.com/ashwanthkumar/gocd-build-github-pull-requests/blob/e37a1954a91f059a5f8f8755884c3ef7e2407218/src/main/java/in/ashwanthkumar/gocd/github/GitHubPRBuildPlugin.java#L283). Instead a "null" is passed in, and the branch [defaults to "master"](https://github.com/ashwanthkumar/git-cmd/blob/4e00e086e6a92ac4706470039ea93393beb26794/src/com/tw/go/plugin/model/GitConfig.java#L80).

Is my understanding right?

Every usage of the branch in GitCmdHelper seems to be using `getEffectiveBranch()`, which should use the branch correctly (if passed in). References: [this](https://github.com/ashwanthkumar/git-cmd/blob/4e00e086e6a92ac4706470039ea93393beb26794/src/com/tw/go/plugin/git/GitCmdHelper.java#L48) and [this](https://github.com/ashwanthkumar/git-cmd/blob/4e00e086e6a92ac4706470039ea93393beb26794/src/com/tw/go/plugin/git/GitCmdHelper.java#L60).

**Comment by ashwanthkumar** [comment]
@arvindsv Yes that's pretty much it.

**Comment by tom--pollard** [comment]
I'd find it extremely useful if it were possible to test PR's that were on release branches, not just master of projects

**Comment by vladistan** [comment]
+1

**Comment by gunnarx** [comment]
What's the status of this @ashwanthkumar ?
Just now it seemed our GoCD setup actually built a PR for another branch than master(?) so was something fixed?  Did you do something?  (Server is version 17.1.0, and I reinstalled the plugin maybe 2 weeks ago or so)

**Comment by ashwanthkumar** [comment]
@gunnarx PRs will be built from any branch, it would just not test it against any other branch. I haven't made any changes for this yet.

**Comment by ashwanthkumar** [comment]
I took some time and got this implemented as part of https://github.com/ashwanthkumar/gocd-build-github-pull-requests/pull/92. 

@gunnarx and others would you like to give it a spin and let me know your thoughts? I'm attaching a manual build of the github PR poller for quickly testing it.

[github-pr-poller.jar.tar.gz](https://github.com/ashwanthkumar/gocd-build-github-pull-requests/files/792688/github-pr-poller.jar.tar.gz)

**Comment by ashwanthkumar** [comment]
Fixed via #92 

Updated version is available via https://github.com/ashwanthkumar/gocd-build-github-pull-requests/releases/tag/v1.3.0
