### ISSUE TITLE
pull request isn't merging with master

### ISSUE THREAD

**Issue by insano10** [ashwanthkumar/gocd-build-github-pull-requests#69]
When a PR triggers the pipeline it doesn't appear to be merging with master. In my repo the PR status says it has merge conflicts that need to be resolved. However the pipeline just builds successfully anyway because it doesn't attempt the merge.

Should it be merging before executing the pipeline?

**Comment by ashwanthkumar** [comment]
@insano10 Sorry for getting back late. We don't test for merge at the moment. We only build the current tree.
