### ISSUE TITLE
SERIOUS: pull request material URL is saved globally, overwriting per-pipeline Stash material URL's

### ISSUE THREAD

**Issue by jefftrimm** [ashwanthkumar/gocd-build-github-pull-requests#78]
I'm using the Stash-specific pull-request plugin, but I suspect this affects all variants.  

If I set up two different pipelines with a pull-request material, and then change the material URL on one of the pipelines, the material URL on other pipelines with a Stash material defined also changes to the same value.

I moved the pipelines into different pipeline groups, and I still see the same behavior.

The URL and config on the pull-request plugin must be pipeline-specific, otherwise it it is impossible to have different pipelines building pull-requests for different Stash/Github/etc. git repos.

**Comment by ashwanthkumar** [comment]
@jefftrimm Would you be able to share a screenshot of the page where you're editing the url? Even if its private via email it's fine.

**Comment by jefftrimm** [comment]
Shot you a mail with screenshots.  Thanks!

**Comment by boothead** [comment]
It seems that the git repo url is also unique?

I followed the instructions and cloned a pipeline and created a material for PRs against one of my git repos. Then I deleted that pipeline due to the upstream one changing. Now it seems I can't re-create the material pointing my repo, even if I change the name. I'm getting:

```
The following error(s) need to be resolved in order to perform this action:

Cannot save SCM, found duplicate SCMs. scintialla-PRs, scintilla-pull-requests
```

scintilla-PRs was the first name (in the deleted pipeline), scintilla-pull-requests is the current name. Both are trying to point to the same github repo url.

**Comment by ashwanthkumar** [comment]
@boothead Yes the repo name is also supposed to be unique. Logically they're a single SCM material unlike the default Git material which can be duplicated everywhere. 

For your specific issue, you can re-use the same `scintilla-PRs` SCM for the new pipeline.

**Comment by boothead** [comment]
That @ashwanthkumar. How can I re-use it though? It was in a deleted pipeline and I don't know how to refer to it now...

**Comment by ashwanthkumar** [comment]
@boothead There's no UI to refer an existing SCM, but you can do it via config.xml AFAIK

In the config.xml look for something like 
```xml
<scm id="c80b64c7-910b-49ff-ba24-e1f49991be01" name="suuchi-pr">
  <pluginConfiguration id="github.pr" version="1" />
  <configuration>
    <property>
      <key>url</key>
      <value>git@github.com:ashwanthkumar/suuchi.git</value>
    </property>
  </configuration>
</scm>
```

Take a note of the `id` attribute. In the respective pipeline use that to refer to that SCM. Check below as an example. 

```xml
<pipeline name="Suuchi-PR" labeltemplate="2.0.${COUNT}-pr" isLocked="false">
<materials>
  <scm ref="c80b64c7-910b-49ff-ba24-e1f49991be01" dest="suuchi">
    <filter>
      <ignore pattern="suuchi-examples/**/*" />
    </filter>
  </scm>
</materials>
.....
</pipeline>
```

HTH.

**Comment by boothead** [comment]
Thanks, that's very helpful! What's the filter/ignore node here for?

**Comment by ashwanthkumar** [comment]
@boothead That's the Blacklist (or Whitelist) box you see in the SCM window below the connection settings.

**Comment by boothead** [comment]
Great, thanks for the help :-)

**Comment by boothead** [comment]
Sorry one more question: Do I have to do anything special to get the github PR updated with the status? I have two stages, with the testing of the binary build from the PR in the first being performed in the second stage.

**Comment by ashwanthkumar** [comment]
@boothead Assuming you're following the instructions as laid out on the [build-status plugin](https://github.com/gocd-contrib/gocd-build-status-notifier#behavior) - you don't have to do anything. 

Check out an example below of how it would look when you've multiple pipelines configured for the PR. Read it as `<pipeline name>/<stage name>` passed ( ✔️  ) or failed ( ✖️ ). 

![screen shot 2016-10-17 at 5 59 45 pm](https://cloud.githubusercontent.com/assets/600279/19437570/9937c8e2-9493-11e6-8fb0-8235259f950a.png)

**Comment by boothead** [comment]
I didn't have the github stuff configured properly. Fixed now. Thanks again :-)

**Comment by ashwanthkumar** [comment]
@jefftrimm @boothead I'm closing this issue. Feel free to re-open in case of any other issues.
