### ISSUE TITLE
Duplicate SCM issue

### ISSUE THREAD

**Issue by mootpt** [ashwanthkumar/gocd-build-github-pull-requests#89]
Unable to use the same repo for multiple pipelines. Is this by design? I have 2 pipelines for Terraform that watch the same repo, just different directories. I am using blacklisting to tell one pipeline to ignore changes in a directory. Is there some sort of work around that will allow me to use the same source for both Pipelines?

**Comment by ashwanthkumar** [comment]
That's by GoCD's design actually :( 

Workaround would be to change the name of the repo. For example, if your material has the following url 

`git@github.com:ashwanthkumar/gocd-build-github-pull-requests` -- you can create another material with `git@Github.com:ashwanthkumar/gocd-build-github-pull-requests`. 

The workaround is based on a hack that GoCD's material is case-sensitive while the actual SCM implementations are not (eg. DNS names are not case-sensitive in this case).

**Comment by mootpt** [comment]
Thanks for the response. Nervous about a work around with casing. :( :+1:  none the less

**Comment by ashwanthkumar** [comment]
i'm closing this issue @mootpt. Feel free to re-open if you've any more questions related to this.
