### ISSUE TITLE
plugin disregards .gitignore

### ISSUE THREAD

**Issue by mvolhontseff** [ashwanthkumar/gocd-build-github-pull-requests#91]
Directories added to .gitignore (e.g., TestResults) aren't ignored.  Cleanup wipes the build root directory clean, which destroys any test results saved within those directories during task execution.

**Comment by ashwanthkumar** [comment]
@mvolhontseff Can you please help me understand which Cleanup are you referring to?

**Comment by mvolhontseff** [comment]
During task execution, if you create a directory "foo" within the working directory, and add that directory to .gitignore, it won't be ignored.  It is deleted.

I would expect this type of behavior when "Clean Working Directory" in the Pipeline's Stage settings is checked.  However, it is not.

**Comment by ashwanthkumar** [comment]
@mvolhontseff Thanks, that helps a bit. Let me explain
- "Clean Working Directory" is a feature of GoCD and not that of the plugin. 
- "Clean Working Directory" AFAIK does something similar to `rm -rf` of the build directory before the SCM plugin (or implementations) are invoked for checking out the materials. 

That's been the functionality of the system so far, and I'm not aware of any workarounds at this point. However, are you using a known build system for your pipeline (like Maven or SBT or Gradle?); if so these systems have a `clean` command or lifecycle that would clear the build directory and not delete everything like "Clean Working Directory" feature. 

But I feel your sentiment towards the feature implementation. Would you be kind enough to start a thread on the gocd mailing list? May be the developers of the tool would be able to give you more context on why it's being the way it works.

**Comment by mvolhontseff** [comment]
I am not using a build system; I'm using the stash pull request plugin to create material, and using python to run tests against the material.

If I use git as material instead (tracking a specific branch), .gitignore works as expected.

Thanks for your feedback on the matter.
