### ISSUE TITLE
Check connection failing with time out message

### ISSUE THREAD

**Issue by danielterabyte** [ashwanthkumar/gocd-build-github-pull-requests#93]
Hi, I am trying to setup this plugin to start pipelines from pull requests but with no success.
 
Here we run behind a proxy and we created a git material that is working on check connection, polling changes in the branch configured and starting our pipeline without any problem.

But when I try to make a github material like README tutorial then the check connection fails with the message: 

> check connection failed. Connection time out: connect

**Comment by danielterabyte** [comment]
Oh, I forgot of tell my specs:

Windows 10
Go 17.2 (in 17.1 happened too)
Agent and Server in same machine
Java 1.8.0_121
Working on a .NET system.

I don't know what is wrong. I just follow every step of the install guide and things goes wrong. 
I am evaluating the use of GoCD over Jenkins for our CD proccess and I really prefer GoCD UI and abstractions but is getting hard to defend with those misteries happening all the time.

**Comment by ashwanthkumar** [comment]
@danielterabyte I can't say I've tried it personally but the Github API library we use seem to honor the default java properties for HTTP proxies. Reference [here](https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html). Since the "Check Connection" runs on the server, you might need to pass these settings to GoCD server via it's `wrapper-properties.conf` file. 

Having said, you can safely ignore the connection errors if you've configured the settings on `~/.github` properly and set `go.plugin.github.pr.populate-details` to `N` so we don't query Github for more information for each PR.

**Comment by danielterabyte** [comment]
@ashwanthkumar, thanks for reply.

I do not found the `wrapper-properties.conf` file. The one that I found was wrapper-server.conf in GoCD Server. 
So, I don't know if this is the right file and I don't know how to set HTTP proxies config using this file. As I said before, the pipeline using a git material is working flawless. But the github material is not.
Is the plugin doing something different than the GoCD core on Check Connection? 

About ignore the connections errors I don't get it too. Correct me if I am wrong:
If the "Check Connection" do not report success it means that GoCD is not able to connect to github and therefore will not identify any changes in repo. Right? 

Sorry about my English, I am still learning.

**Comment by ashwanthkumar** [comment]
> About ignore the connections errors I don't get it too. Correct me if I am wrong:
If the "Check Connection" do not report success it means that GoCD is not able to connect to github and therefore will not identify any changes in repo. Right?

Git material uses `git` client to verify the check connection while `Github` material pools the Github API and it doesn't use `git` client but a Java based Github API library that's part of the plugin. Like any JVM based process it takes HTTP proxy details via `http.proxyHost` and `http.proxyPort` system properties. 

> I do not found the wrapper-properties.conf file. The one that I found was wrapper-server.conf in GoCD Server.

Check the official documentation [here](https://docs.gocd.io/current/installation/install/server/windows.html#overriding-default-startup-arguments-and-environment) on how to set up additional properties for the server. 

I'm sorry we don't have a way to do this in the UI (at least AFAIK) 😞

**Comment by ashwanthkumar** [comment]
I almost forgot -- If you're using Github PR material, you need to do the above steps for all Agents as well, as described [here](https://docs.gocd.io/current/installation/install/agent/windows.html#overriding-default-startup-arguments-and-environment).

**Comment by danielterabyte** [comment]
@ashwanthkumar thank you very much. With the last two responses I hack around and now I'm able to connect a github material succesfully.

If somebody face the same problem, the way I solved was, following the @ashwanthkumar tips:

1- Create a config/wrapper-properties.conf inside GoSever instalation folder;
2- Create a config/wrapper-properties.conf inside GoAgent instalation folder;
3- Put inside of both files above the following content, for example:

`wrapper.java.additional.a=-Dhttp.proxyHost=192.xxx.x.x`
`wrapper.java.additional.b=-Dhttp.proxyPort=3128`
`wrapper.java.additional.c=-Dhttps.proxyHost=192.xxx.x.x`
`wrapper.java.additional.d=-Dhttps.proxyPort=3128`

Where `a`, `b`, `c`, `d` are numbers of the additional JVM args like explained [here](https://docs.gocd.io/current/installation/install/agent/windows.html#overriding-default-startup-arguments-and-environment)

In my case it became 5, 6, 7, 8. Make sure to change those `x` to your proxy IP too.

That's it. Problem solved.

Thank you again.
