### ISSUE TITLE
Lists only the top commit instead of listing all the commits since last build

### ISSUE THREAD

**Issue by ericmm** [ashwanthkumar/gocd-build-github-pull-requests#95]
List of changes shows only the top commit instead of showing all the commits since last build. This isn't a true reflection of what the build is running with.

Go version: 15.2.0(2248-c1f90a6aa3192a)
OS: macOS Sierra 10.12.3
plugin version: 1.3.1

Reproduce step:
 - commit one change to one branch locally
 - commit another change to the same branch locally
 - push these two changes to remote
The pipeline triggers but only the last commit is listed in the 'Changes' dropdown.

**Comment by ashwanthkumar** [comment]
@ericmm Would you be please kind enough to test the changes as part of https://github.com/ashwanthkumar/gocd-build-github-pull-requests/pull/96 for this issue?

**Comment by ericmm** [comment]
thanks @ashwanthkumar, will test it out on Monday, have a nice weekend.

**Comment by ericmm** [comment]
@ashwanthkumar, it does not work as expected. 
I cloned the source and built a new 'git-fb-poller-1.3.1.jar' file from the master, then I removed the old jar and used the new one and restarted the Go Server. It still listed only one change in the drop down.

**Comment by ashwanthkumar** [comment]
@ericmm Did you build it out of master branch? If so, please checkout the `fix-95` branch and build a JAR out of that. The PR hasn't been merged yet. 

### How does it work?
When we send a PR (a new PR being opened on a repo), it would only show the latest commit (since we wouldn't know what was the last built commit hash). Any consecutive pushes to the same PR with multiple commits will show up separately in the 'Changes' drop down.

**Comment by ericmm** [comment]
Thanks @ashwanthkumar, I thought it was merged to master branch, re-tested using fix-95 branch, it works and I can see multiple commits in the 'Changes' drop down now. 

BTW, when can we have an official release?  :)

**Comment by ashwanthkumar** [comment]
Super 👍 

Thanks @ericmm. I'm going to cut out a release with those changes in a few minutes.

**Comment by ashwanthkumar** [comment]
@ericmm The release [v1.3.2](https://github.com/ashwanthkumar/gocd-build-github-pull-requests/releases/tag/v1.3.2) contains this fix.

**Comment by ericmm** [comment]
Great, thanks!
