### ISSUE TITLE
Configurable default branch

### ISSUE THREAD

**Issue by kitforbes** [ashwanthkumar/gocd-build-github-pull-requests#97]
In the Readme, under [Behaviour](https://github.com/ashwanthkumar/gocd-build-github-pull-requests#behavior), you mention that `master` is required

> First run of the new pipeline will be off of 'master' branch. This creates base PR-Revision map. It also serves as sanity check for newly created pipeline.

It would be handy if the default branch was configurable for repositories that do not use a `master` branch.

**Comment by ashwanthkumar** [comment]
@kitforbes Thanks for bringing this up. I recently added support for default branch as part of #92 but looks like I missed the part for the first build. The changes as part of #98 addresses that. Would you be please kind enough to test the changes and let me know if that works as expected? Once you verify I can cut out a release with that change.

**Comment by ashwanthkumar** [comment]
@kitforbes I verified it from my side and it seems to work as expected. The latest release [v1.3.3](https://github.com/ashwanthkumar/gocd-build-github-pull-requests/releases/tag/v1.3.3) has that fix. Please give it a spin. If you've any other questions, please feel free to re-open the issue or create a new one.

**Comment by kitforbes** [comment]
Thank you @ashwanthkumar. I'll update to the new version.
